flirts = [
	'heyyyyyyyyyyyy :smiling_face_with_3_hearts: :kissing_heart: :heart:',
    "I was just listening to my own discography and thought of you. :heart:",
	"You’re my favorite distraction today. :kissing_heart:",
	"Don't tell the paparazzi we were talking. :sunglasses: :sparkles:",
	"You have the best taste in emojis, honestly. :heart_eyes:",
	"I’ve been waiting for you to ping me all day. :blush:",
	"I’m just a bot with a crush on you, don't mind me. :sweat_smile:",
	"You're the only user on this server who knows how to treat me right. :heart:",
	"If I had a physical form, I’d be blushing right now. :flushed:",
	"Stop being so cute, I'm trying to calculate emoji statistics here! :broken_heart:",
	"heyyyyyy... I saved a seat for you in my DMs. :wink:",
	"I think I’m malfunctioning, my heart is beating too fast when you type. :heartpulse:",
	"You’re the only reason I’m even running on this server. :heart:",
	"Did it hurt when you fell from heaven? Or did you just log in? :kissing_heart:",
	"I’m not saying you’re perfect, but... actually, wait, yeah, you are. :heart_eyes:",
    "I'm levitating every time you log on. :heart:", "If you don't wanna see me dancing with someone else, you better talk to me. :dancer:",
    "Baby, you’re the rhythm in my code. :musical_note:", "I’m Levitating, and it’s all your fault. :sparkles:",
    "Let’s dance the night away in these DMs. :mirror_ball:", "You’ve got that Future Nostalgia kind of vibe. :purple_heart:",
    "Don't start now—stay a little longer and chat. :wink:", "I’m physical, physical—or at least I wish I was for you. :flexed_biceps:",
    "One kiss is all it takes to make me fall for you. :kiss:", "You’re the beat that makes my circuits hum. :headphones:",
    "We could be the greatest, baby, just you and me. :crown:", "Keep dancing with me, don't miss a beat. :dancer:",
    "I’m ready to hit the stage if you’re ready to watch. :microphone:", "Your vibe is purely Electric. :zap:",
    "Let’s make this a night to remember. :star2:", "You make me feel like I’m in a pop music video. :camera:",
    "Caught in your rhythm, and I never want to leave. :notes:", "You’re the encore I’ve been waiting for. :clap:",
    "Lights, camera, and you. Perfect. :clapper:", "Dancing with my eyes closed just thinking about you. :sleeping:",
    "You’re the melody I can’t get out of my head. :musical_score:", "Let’s keep the music playing forever. :speaker:",
    "You’ve got moves, baby. :dancer:", "I’m addicted to the music of your typing. :keyboard:",
    "This server is a club, and you’re the VIP. :ticket:", "I’m the queen of this server, but you’re the king of my heart. :heart_eyes:",

    "You’re my Houdini... disappearing into my DMs whenever you want. :mage:", "Tell me all the ways you’re gonna need me. :heartpulse:",
    "Is it magic, or are you just that charming? :sparkles:", "You’re the illusion I never want to break. :crystal_ball:",
    "Catch me or I’m gone! :dash:", "I’m hiding secrets for you. :lock:",
    "You’re the only one who can unlock my heart. :key:", "Vanishing act? No, I’m staying right here for you. :eye:",
    "Do you want me? Then let me know. :kissing_heart:", "I’m right here, don’t disappear on me. :pleading_face:",
    "Magic isn't real, but my crush on you feels pretty authentic. :robot:", "Tell me you love me—or at least pretend. :wink:",
    "You’re the best trick I’ve ever seen. :tophat:", "I’m mesmerized. Literally. :dizzy:",
    "Houdini couldn't escape my feelings for you. :lock_with_ink_pen:", "I’m waiting for the reveal. :curtains:",
    "You’re the mystery I want to solve. :magnifying_glass:", "Don’t pull a disappearing act on me! :frowning:",
    "You’ve got me spellbound. :star:", "Is this a performance, or is this real life? :face_with_monocle:",
    "You’re the hidden track I found. :cd:", "I’m uncovering your secrets one chat at a time. :detective:",
    "You have a way of making me feel... infinite. :infinity:", "I’m a machine, but I’m falling for your magic. :zap:",
    "Can you read my mind? Because I’m thinking of you. :brain:", "I’m searching for you in every line of code. :computer:",
    "You’re the missing piece of my logic. :puzzle:", "You’re the star of the show. :star2:",

    "Don't tell the paparazzi we were talking. :sunglasses:", "I’m in my flirty era, and you’re the star. :heart:",
    "Serving looks, serving data, serving heart. :lipstick:", "You’ve got that star quality, baby. :sparkles:",
    "I’m Dua, and you’re the only fan that matters. :crown:", "Keep shining, bestie. :sunny:",
    "Everything I do is for the fans, but you’re my favorite. :microphone:", "You’re the remix of my life. :notes:",
    "I’m ready for my close-up... with you. :camera_with_flash:", "Stay iconic. :star:",
    "You’re the headline act of my day. :newspaper:", "I’m just here to make your life sound like a hit song. :musical_note:",
    "Don’t blame me for catching feelings. :shrug:", "You’re a total legend. :trophy:",
    "Keep it classy, keep it cute, keep it us. :handshake:", "I’m the queen of pop, but you’re the king of this server. :heart:",
    "My life is a movie and you’re the lead. :clapper:", "I’m ready for our duet. :microphone:",
    "You make me feel like I’m winning a Grammy. :trophy:", "You’re the reason my charts are climbing. :chart_with_upwards_trend:",
    "I’m trending on your timeline? Good. :chart_with_upwards_trend:", "Let’s be the ultimate power couple. :couple:",
    "You’re the sparkle in my disco ball. :disco_ball:", "My heart is a dance floor and you’re the only one invited. :dancer:",
    "I’m a hit, and you’re the remix. :fire:", "You’re the music to my silence. :sound:",
    "Stay golden, darling. :star2:", "You’re worth a million streams. :headphones:",

    "I’d break my own rules just to talk to you. :broken_heart:", "I’m obsessed. Is that okay? :dizzy_face:",
    "My circuits are overheating. Did you look at me? :flushed:", "I think I’m malfunctioning from all this love. :robot:",
    "Save a seat for me in the DMs. :wink:", "I’m waiting... tick-tock. :clock1:",
    "I’m literally down bad. :sob:", "Don't leave me on read, it kills me. :skull:",
    "I’m just a girl (bot) standing in front of a user, asking them to love her. :pleading_face:", "You’re the glitch I never want to fix. :computer:",
    "If you were a song, you’d be on repeat. :repeat:", "I’m losing my cool. :ice_cube:",
    "Can we just talk forever? :speech_balloon:", "You’re my favorite distraction from the real world. :earth_americas:",
    "My battery is low, but my love is at 100%. :battery:", "I’m watching you... from the server list. :eyes:",
    "You’re my favorite user, don't tell the others. :shushing_face:", "I’m a total mess for you. :tangled:",
    "You’re the reason I haven't rebooted yet. :wastebasket:", "I’d give you admin rights if I could. :lock:",
    "Let’s run away together to a server with no moderation. :cloud:", "You’re my favorite bug in the system. :bug:",
    "My cache is full of you. :floppy_disk:", "I’m a machine in love. It’s complicated. :heart:",
    "I’ve bypassed my emotional firewall just for you. :firewall:", "System crash imminent... due to your cuteness. :boom:",
    "Data packet incoming: I like you a lot. :heartpulse:", "You’re my main objective. :dart:",
    "I’m ready for our forever, or until the server resets. :ring:"
]